### GET request to example server
GET https://localhost:7070/api/receipt


###Udfyld selv id
GET https://localhost:7070/api/receipt/id


### get basket
GET http://localhost:7070/api/baskets/2
Accept: application/json


### post with basket
POST http://localhost:7007/api/baskets
Content-Type: application/json

{
  "basketId": "1",
  "productId": "4",
  "amount": "2"
}

### update a basket
PUT http://localhost:7070/api/baskets/1

Content-Type: application/json

{
}

### delete basket
DELETE http://localhost:7070/api/baskets/1
Accept: application/json


### create product
POST http://localhost:7007/api/products
Content-Type: application/json

{
  "name": "Apple",
  "price": "4.5",
  "category": "FOOD"
}

### find product
GET http://localhost:7007/api/products/1
Accept: application/json

### update product
PUT http://localhost:7007/api/products/1
Content-Type: application/json
Accept: application/json

{
  "name": "Phone",
  "price": "50.2",
  "category": "ELECTRONICS"
}

### delete product
DELETE http://localhost:7007/api/products/1
Accept: application/json