### GET request to example server
GET https://localhost:7070/api/receipt


###Udfyld selv id
GET https://localhost:7070/api/receipt/id


### get basket
GET http://localhost:7070/api/baskets/2
Accept: application/json


### post with basket
POST http://localhost:7070/api/baskets
Content-Type: application/json

{
}

### update a basket
PUT http://localhost:7070/api/baskets/1

Content-Type: application/json

{
}

### delete basket
DELETE http://localhost:7070/api/baskets/1
Accept: application/json

### add product to basket
PUT http://localhost:7070/api/baskets/1/product/1

Content-Type: application/json

{
}