//API Endpoints


//Basket
### post with basket
POST https://{{url}}/baskets
Content-Type: application/json

{
  "basketId": "1",
  "productId": "2",
  "amount": "5"
}

### get basket
GET https://{{url}}/baskets/1
Accept: application/json


### delete basket
DELETE https://{{url}}/baskets/1
Accept: application/json


//Product
### create product
POST https://{{url}}/products
Content-Type: application/json

{
  "name": "Apple",
  "price": "4.5",
  "category": "FOOD"
}

### find product
GET https://{{url}}/products/1
Accept: application/json

### find all product
GET https://{{url}}/products
Accept: application/json

### update product
PUT https://{{url}}/products/1
Content-Type: application/json
Accept: application/json

{
  "name": "Phone",
  "price": "50.2",
  "category": "ELECTRONICS"
}

### delete product
DELETE https://{{url}}/products/1
Accept: application/json


//Receipt