//API Endpoints

//Security Endpoints
### register a user
POST http://{{url}}/auth/register

{
    "username": "user1",
    "password": "pass12345"
}


### login
POST http://{{url}}/auth/login

{
    "username": "ADMIN",
    "password": "1234"
}

### test user token
GET http://{{url}}/protected/user_demo
AUTHORIZATION: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIlNvZnVzIExhcnNlblwiIiwic3ViIjoidXNlcjEiLCJleHAiOjE3NjEzMjkzNTAsInJvbGVzIjoiVXNlciIsInVzZXJuYW1lIjoidXNlcjEifQ.EpvzE1NMMMrid28iokHI6Hv0mdzDmurEXw6Gqiyj7tc

### test admin token
GET http://{{url}}/protected/admin_demo
AUTHORIZATION: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIlNvZnVzIExhcnNlblwiIiwic3ViIjoidXNlcjEiLCJleHAiOjE3NjEzMjkzNTAsInJvbGVzIjoiVXNlciIsInVzZXJuYW1lIjoidXNlcjEifQ.EpvzE1NMMMrid28iokHI6Hv0mdzDmurEXw6Gqiyj7tc



//Basket & Product Endpoints
### post a product to specific basket
POST https://{{url}}/baskets
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIlNvZnVzIExhcnNlblwiIiwic3ViIjoidXNlcjEiLCJleHAiOjE3NjEzODAwNTQsInJvbGVzIjoiVXNlciIsInVzZXJuYW1lIjoidXNlcjEifQ.podGRgtnsMtNjbRDF6noPqXlvh-8bLAZevgAPu5bxyk

{
  "basketId": "1",
  "productId": "1",
  "amount": "10"
}


### create a product
POST https://{{url}}/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIlNvZnVzIExhcnNlblwiIiwic3ViIjoidXNlcjEiLCJleHAiOjE3NjEzODAwNTQsInJvbGVzIjoiVXNlciIsInVzZXJuYW1lIjoidXNlcjEifQ.podGRgtnsMtNjbRDF6noPqXlvh-8bLAZevgAPu5bxyk

{
  "name": "Apple",
  "price": "4.5",
  "category": "FOOD"
}

### find a specific product
GET https://{{url}}/products/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIlNvZnVzIExhcnNlblwiIiwic3ViIjoidXNlcjEiLCJleHAiOjE3NjEzODAwNTQsInJvbGVzIjoiVXNlciIsInVzZXJuYW1lIjoidXNlcjEifQ.podGRgtnsMtNjbRDF6noPqXlvh-8bLAZevgAPu5bxyk

### find all existing products
GET https://{{url}}/products
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIlNvZnVzIExhcnNlblwiIiwic3ViIjoidXNlcjEiLCJleHAiOjE3NjEzODAwNTQsInJvbGVzIjoiVXNlciIsInVzZXJuYW1lIjoidXNlcjEifQ.podGRgtnsMtNjbRDF6noPqXlvh-8bLAZevgAPu5bxyk

### update a product
PUT https://{{url}}/products/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIlNvZnVzIExhcnNlblwiIiwic3ViIjoidXNlcjEiLCJleHAiOjE3NjEzODAwNTQsInJvbGVzIjoiVXNlciIsInVzZXJuYW1lIjoidXNlcjEifQ.podGRgtnsMtNjbRDF6noPqXlvh-8bLAZevgAPu5bxyk

{
  "name": "Phone",
  "price": "50.2",
  "category": "ELECTRONICS"
}

### delete product
DELETE https://{{url}}/products/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIlNvZnVzIExhcnNlblwiIiwic3ViIjoidXNlcjEiLCJleHAiOjE3NjEzODAwNTQsInJvbGVzIjoiVXNlciIsInVzZXJuYW1lIjoidXNlcjEifQ.podGRgtnsMtNjbRDF6noPqXlvh-8bLAZevgAPu5bxyk


### find all products from specific basket
GET https://{{url}}/basketproducts/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIlNvZnVzIExhcnNlblwiIiwic3ViIjoidXNlcjEiLCJleHAiOjE3NjEzODAwNTQsInJvbGVzIjoiVXNlciIsInVzZXJuYW1lIjoidXNlcjEifQ.podGRgtnsMtNjbRDF6noPqXlvh-8bLAZevgAPu5bxyk

//Receipt