//API Endpoints


//Basket Endpoints
### post a product to specific basket
POST https://{{url}}/baskets
Content-Type: application/json

{
  "basketId": "1",
  "productId": "1",
  "amount": "10"
}

### get a specific basket
GET https://{{url}}/baskets/1
Accept: application/json


### delete a basket
DELETE https://{{url}}/baskets/1
Accept: application/json


//Product Endpoints
### create a product
POST https://{{url}}/products
Content-Type: application/json

{
  "name": "Apple",
  "price": "4.5",
  "category": "FOOD"
}

### find a specific product
GET https://{{url}}/products/1
Accept: application/json

### find all existing products
GET https://{{url}}/products
Accept: application/json

### update a product
PUT https://{{url}}/products/1
Content-Type: application/json
Accept: application/json

{
  "name": "Phone",
  "price": "50.2",
  "category": "ELECTRONICS"
}

### delete product
DELETE https://{{url}}/products/1
Accept: application/json


//Basket & Product Endpoints
### find all products from specific basket
GET https://{{url}}/basketproducts/1
Accept: application/json

//Receipt