

###
POST http://{{url}}/auth/login

{
    "username": "ADMIN",
    "password": "1234"
}

###
POST http://{{url}}/auth/register

{
    "username": "user1",
    "password": "pass12345"
}

###
GET http://{{url}}/protected/user_demo
AUTHORIZATION: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIlNvZnVzIExhcnNlblwiIiwic3ViIjoidXNlcjEiLCJleHAiOjE3NjEzMjkzNTAsInJvbGVzIjoiVXNlciIsInVzZXJuYW1lIjoidXNlcjEifQ.EpvzE1NMMMrid28iokHI6Hv0mdzDmurEXw6Gqiyj7tc

###
GET http://{{url}}/protected/admin_demo
AUTHORIZATION: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIlNvZnVzIExhcnNlblwiIiwic3ViIjoidXNlcjEiLCJleHAiOjE3NjEzMjkzNTAsInJvbGVzIjoiVXNlciIsInVzZXJuYW1lIjoidXNlcjEifQ.EpvzE1NMMMrid28iokHI6Hv0mdzDmurEXw6Gqiyj7tc

